package com.olive.homly.navigation

const val  ROUTE_HOME="home"
const val ROUTE_SPLASH="splash"
const val ROUTE_LOGIN="login"
const val ROUTE_SIGNUP="sign up"
const val ROUTE_CART="cart"
const val ROUTE_DELIVERY="delivery"
const val ROUTE_ORDER="place_order"
const val ROUTE_CATEGORIES="product_categories"
const val ROUTE_DETAILS="product_details"
const val ROUTE_LIST="product_list"
const val ROUTE_BATHROOM = "bathroom"
const val ROUTE_BEDROOM = "bedroom"
const val ROUTE_DINING = "dining"
const val ROUTE_FOYER = "foyer"
const val ROUTE_GARAGE = "garage"
const val ROUTE_HOMEOFFICE = "homeoffice"
const val ROUTE_KITCHEN = "kitchen"
const val ROUTE_LAUNDRY = ""
const val ROUTE_LIVINGROOM = "livingroom"
const val ROUTE_OUTDOORS = "outdoors"
